# version: "3.9"

# services:
#   web:
#     build: .
#     container_name: fastapi-app
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/app/app
#     command: >
#       uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://testuser:testpass@db:5432/testdb

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
